export global Pallete {
    out property <color> primary: blue;
}

export global Navigation {
    out property <int> dashboard: 0;
    out property <int> devices: 1;
    out property <int> reports: 2;
    out property <int> settings: 3;
}

export enum Menus {
    ECDSA_Validation,
    Interfaces_Validation,
    Cipher_Depreciation_Validation,
    Continuous_Cache_Poisoning_Monitoration,
    VLAN_Segmentation_Inspector,
    Quick_Topology_Scanner,
    Cable_Test,
    DNS_Hijacking_Test,
    Bandwidth_Test,
    Password_Breaker //Samba tu
}
